
export const REQUEST_USERS = "REQUEST_USERS";
export const FETCH_USERS = "FETCH_USERS";
export const ERRORS = "ERRORS";

export const POST_USER_PROFILE = "POST_USER_PROFILE"
export const ERROR_UPLOADING_PROFILE = "ERROR_UPLOADING_PROFILE";
export const SPINNER_UPLOADING_PROFILE = "SPINNER_UPLOADING_PROFILE"